//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: code.h
//  Source: code.idl
//  Generated: Tue Oct 30 22:02:02 2018
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _CODE_H_
#define _CODE_H_

#include "sacpp_mapping.h"


namespace CodeData
{
   struct Code;

   struct Code
   {
         DDS::Long coderID;
         DDS::String_mgr uploadTime;
         DDS::String_mgr fileName;
         DDS::String_mgr codeContent;
   };

   typedef DDS_DCPSStruct_var < Code> Code_var;
   typedef DDS_DCPSStruct_out < Code> Code_out;
}




#endif
