//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: code.cpp
//  Source: code.idl
//  Generated: Tue Oct 30 22:02:02 2018
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************

#include "code.h"




